import { PendingLink } from "@/components/common/PendingLink";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-3xl">{eyebrow ? <p className="text-xs font-bold uppercase tracking-[0.22em] text-papaipay-green">{eyebrow}</p> : null}<h1 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-papaipay-ink sm:text-3xl">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>{action}</header>;
}
export function Card({ children, className = "", id }: { children: React.ReactNode; className?: string; id?: string }) { return <section id={id} className={`min-w-0 scroll-mt-28 rounded-2xl border border-slate-200/70 bg-white/90 p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)] sm:p-6 ${className}`}>{children}</section>; }
export function KpiCard({ label, value, helper, trend }: { label: string; value: string; helper: string; trend?: string }) { return <Card className="min-w-0"><p className="truncate text-[0.65rem] font-semibold uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-3 text-xl font-semibold tracking-[-0.04em] sm:text-3xl">{value}</p><p className="mt-2 text-[0.72rem] leading-5 text-slate-500 sm:text-sm">{helper}</p>{trend ? <p className="mt-4 inline-flex rounded-full bg-emerald-50 px-2 py-1 text-[0.68rem] font-semibold text-papaipay-green">{trend}</p> : null}</Card>; }
export function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex whitespace-nowrap rounded-md border border-slate-200 bg-slate-50 px-2.5 py-1 text-[0.68rem] font-bold uppercase tracking-wide text-papaipay-green">{children}</span>; }
export function BackLink({ href, label = "Back" }: { href: string; label?: string }) { return <PendingLink href={href} pendingLabel="Opening..." className="inline-flex items-center text-sm font-bold text-papaipay-green hover:text-papaipay-ink">← {label}</PendingLink>; }
export function SearchFilter({ placeholder = "Search", filter = "All statuses" }: { placeholder?: string; filter?: string }) { return <div className="flex flex-col gap-3 sm:flex-row"><input className="min-h-11 flex-1 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-papaipay-green" placeholder={placeholder} /><select className="min-h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-600 outline-none focus:border-papaipay-green"><option>{filter}</option><option>Verified</option><option>Pending</option><option>Completed</option><option>Open</option></select></div>; }
export function TableWrap({ children }: { children: React.ReactNode }) { return <div className="min-w-0 max-w-full overflow-hidden rounded-2xl border border-slate-200/70 bg-white"><div className="max-w-full overflow-x-auto overscroll-x-contain"><table className="w-full min-w-max divide-y divide-slate-100 text-left text-sm">{children}</table></div></div>; }
export function Th({ children }: { children: React.ReactNode }) { return <th className="whitespace-nowrap px-4 py-3 text-[0.68rem] font-bold uppercase tracking-wide text-slate-400">{children}</th>; }
export function Td({ children }: { children: React.ReactNode }) { return <td className="max-w-xs whitespace-normal break-words px-4 py-4 text-slate-600">{children}</td>; }
export function ProgressBar({ value }: { value: number }) { return <div className="h-2.5 min-w-28 overflow-hidden rounded-md bg-slate-100"><div className="h-full rounded-md bg-papaipay-green" style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
export function InfoGrid({ items }: { items: { label: string; value: string }[] }) { return <div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <div key={item.label} className="min-w-0 rounded-md border border-slate-100 bg-slate-50/80 p-3"><p className="text-[0.68rem] font-bold uppercase tracking-wide text-slate-400">{item.label}</p><p className="mt-1 min-w-0 break-words font-bold text-slate-800">{item.value}</p></div>)}</div>; }
